import { NextResponse } from 'next/server';

import { supabaseAdmin } from '@/lib/supabase/admin';
import type { Json } from '@/lib/supabase/types';
import { parseWebhookPayload } from '@/lib/sarvam';
import { parseOutputVariables } from '@/lib/agent-config';
import { parseCallbackPreference } from '@/lib/date-parser';

/**
 * POST /api/agent/webhook — Sarvam calls this when the agent call ends.
 *
 * Payload: { attempt_id, status, duration, interaction_id, final_agent_variables,
 *            interaction_transcript, webhook_config: { metadata: { lead_id } } }
 *
 * Updates the `agent_calls` row, writes a rich structured note to the lead
 * timeline, and updates lead status based on qualification_status.
 */
export async function POST(request: Request) {
  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON.' }, { status: 400 });
  }

  const parsed = parseWebhookPayload(payload);
  if (!parsed.success) {
    console.error('[webhook] validation failed', parsed.error);
    return NextResponse.json(
      { error: 'Invalid webhook payload.' },
      { status: 422 }
    );
  }

  const {
    attempt_id,
    status,
    duration,
    interaction_id,
    final_agent_variables,
    interaction_transcript,
    webhook_config,
  } = parsed.data;

  /* Metadata is whatever we handed Sarvam at dial time and it echoes back */
  const rawLeadId = webhook_config?.metadata?.lead_id;
  const leadId = typeof rawLeadId === 'string' ? rawLeadId : null;
  if (!leadId) {
    console.error('[webhook] missing lead_id in metadata');
    return NextResponse.json({ error: 'Missing lead_id.' }, { status: 422 });
  }

  const STATUS_MAP: Record<string, 'connected' | 'no_answer' | 'busy' | 'failed'> = {
    connected: 'connected',
    no_answer: 'no_answer',
    busy: 'busy',
    failed: 'failed',
  };

  const callStatus = STATUS_MAP[status] ?? 'failed';
  if (!(status in STATUS_MAP)) {
    console.warn(
      `[webhook] unrecognised Sarvam status "${status}" for attempt ${attempt_id} — recording as failed`
    );
  }

  const durationSeconds = duration ?? 0;

  // Parse all structured output from the agent
  const parsed_output = parseOutputVariables(final_agent_variables ?? {});
  const {
    summary,
    disposition,
    businessName,
    ownerName,
    hasWebsite,
    budgetRange,
    callbackPreference,
    interestReason,
    objection,
  } = parsed_output;

  // Update the agent_calls row with full data
  const { error: updateError } = await supabaseAdmin
    .from('agent_calls')
    .update({
      call_status: callStatus,
      interaction_id: interaction_id ?? null,
      duration_seconds: durationSeconds || null,
      summary: summary || null,
      disposition: disposition || null,
      transcript: (interaction_transcript ?? []) as Json,
      agent_variables: (final_agent_variables ?? {}) as Json,
      ended_at: new Date().toISOString(),
    })
    .eq('attempt_id', attempt_id);

  if (updateError) {
    console.error('[webhook] failed to update agent_calls', updateError);
    return NextResponse.json(
      { error: 'Could not update call record.' },
      { status: 500 }
    );
  }

  /*
    Everything past this point is bookkeeping on the lead, and a failure in it
    must not make us answer Sarvam with a 500 — they retry on non-2xx, and a
    retry would re-run the `agent_calls` update and duplicate timeline entries.
  */
  const problems: string[] = [];

  // Build a rich structured note body for the timeline
  const noteBody = buildNoteBody({
    callStatus,
    durationSeconds,
    summary,
    disposition,
    businessName,
    ownerName,
    hasWebsite,
    budgetRange,
    callbackPreference,
    interestReason,
    objection,
  });

  // Write the note to the lead timeline
  const { error: noteError } = await supabaseAdmin.from('lead_activities').insert({
    lead_id: leadId,
    author_id: null, // system-generated by voice agent
    kind: 'agent_call',
    body: noteBody,
    meta: {
      attempt_id,
      call_status: callStatus,
      duration_seconds: durationSeconds || null,
      disposition,
      has_website: hasWebsite,
      budget_range: budgetRange,
      callback_preference: callbackPreference,
      interest_reason: interestReason,
      objection,
      business_name: businessName,
      owner_name: ownerName,
    },
  });
  if (noteError) problems.push(`call note: ${noteError.message}`);

  /*
    Move the stage and set follow-up time based on conversation outcome.
  */
  let nextStatus: 'contacted' | 'qualified' | 'rejected' | null = null;
  if (callStatus === 'connected') {
    if (disposition === 'qualified' || disposition === 'interested') {
      nextStatus = 'qualified';
    } else if (disposition === 'not_interested') {
      nextStatus = 'rejected';
    } else {
      nextStatus = 'contacted';
    }
  }

  const followUpDate = callbackPreference ? parseCallbackPreference(callbackPreference) : null;

  if (nextStatus || followUpDate) {
    const { data: current, error: currentError } = await supabaseAdmin
      .from('leads')
      .select('status')
      .eq('id', leadId)
      .maybeSingle();

    if (currentError) problems.push(`read stage: ${currentError.message}`);

    const previousStatus = current?.status ?? null;

    if (previousStatus !== nextStatus || followUpDate) {
      const updatePayload: { status?: 'contacted' | 'qualified' | 'rejected'; next_follow_up_at?: string } = {};
      if (previousStatus !== nextStatus && nextStatus) {
        updatePayload.status = nextStatus;
      }
      if (followUpDate) {
        updatePayload.next_follow_up_at = followUpDate.toISOString();
      }

      const { error: statusError } = await supabaseAdmin
        .from('leads')
        .update(updatePayload)
        .eq('id', leadId);

      if (statusError) {
        problems.push(`set stage/followup: ${statusError.message}`);
      } else {
        if (previousStatus !== nextStatus && nextStatus) {
          const { error: logError } = await supabaseAdmin
            .from('lead_activities')
            .insert({
              lead_id: leadId,
              author_id: null,
              kind: 'status_change',
              body: null,
              meta: { from: previousStatus, to: nextStatus, source: 'agent' },
            });
          if (logError) problems.push(`stage note: ${logError.message}`);
        }

        if (followUpDate) {
          const { error: logError } = await supabaseAdmin
            .from('lead_activities')
            .insert({
              lead_id: leadId,
              author_id: null,
              kind: 'field_update',
              body: `Scheduled next follow-up for ${followUpDate.toLocaleString('en-IN')}`,
              meta: { fields: ['next_follow_up_at'] },
            });
          if (logError) problems.push(`followup note: ${logError.message}`);
        }
      }
    }
  }

  if (problems.length > 0) {
    console.error(
      `[webhook] attempt ${attempt_id} recorded, but lead bookkeeping failed — ${problems.join('; ')}`
    );
  }

  return NextResponse.json({ ok: true });
}

// ─────────────────────────────────────────────────────────────────────────────
// Rich note builder
// ─────────────────────────────────────────────────────────────────────────────

const CALL_STATUS_LABEL: Record<string, string> = {
  connected: 'Call connected',
  no_answer: 'No answer',
  busy: 'Line was busy',
  failed: 'Call failed',
};

const DISPOSITION_LABEL: Record<string, string> = {
  qualified: '✅ Qualified — agreed to follow-up',
  interested: '🔥 Interested — open to a website',
  callback_later: '📅 Callback requested',
  not_interested: '❌ Not interested',
  wrong_number: '📵 Wrong number',
  no_decision_maker: '👤 Decision maker not available',
  unclear: '❓ Unclear outcome',
};

const HAS_WEBSITE_LABEL: Record<string, string> = {
  yes: 'Has a website',
  no: 'No website',
  outdated: 'Has an outdated website',
  unknown: 'Unknown',
};

const BUDGET_LABEL: Record<string, string> = {
  under_5k: 'Under ₹5,000',
  '5k_10k': '₹5,000 – ₹10,000',
  '10k_20k': '₹10,000 – ₹20,000',
  above_20k: 'Above ₹20,000',
  unknown: 'Not discussed',
};

function formatDuration(seconds: number): string {
  const whole = Math.round(seconds);
  if (whole < 60) return `${whole}s`;
  const minutes = Math.floor(whole / 60);
  const rest = whole % 60;
  return rest ? `${minutes}m ${rest}s` : `${minutes}m`;
}

interface NoteBuilderParams {
  callStatus: string;
  durationSeconds: number;
  summary: string;
  disposition: string | null;
  businessName: string | null;
  ownerName: string | null;
  hasWebsite: string | null;
  budgetRange: string | null;
  callbackPreference: string | null;
  interestReason: string | null;
  objection: string | null;
}

/**
 * Build the rich body text for the `lead_activities` note.
 * Formatted so a human can scan it quickly before making the follow-up call.
 */
function buildNoteBody(p: NoteBuilderParams): string {
  const lines: string[] = [];

  // Headline: outcome + duration
  const statusLabel = CALL_STATUS_LABEL[p.callStatus] ?? p.callStatus;
  const durationStr = p.durationSeconds > 0 ? ` · ${formatDuration(p.durationSeconds)}` : '';
  lines.push(`${statusLabel}${durationStr}`);

  if (p.callStatus !== 'connected') {
    return lines.join('\n');
  }

  // Disposition
  if (p.disposition) {
    lines.push('');
    lines.push(DISPOSITION_LABEL[p.disposition] ?? p.disposition);
  }

  // Call summary from the agent
  if (p.summary) {
    lines.push('');
    lines.push('📝 Call Summary');
    lines.push(p.summary);
  }

  // Structured info
  const details: string[] = [];
  if (p.ownerName) details.push(`Spoke to: ${p.ownerName}`);
  if (p.hasWebsite) details.push(`Website: ${HAS_WEBSITE_LABEL[p.hasWebsite] ?? p.hasWebsite}`);
  if (p.budgetRange) details.push(`Budget: ${BUDGET_LABEL[p.budgetRange] ?? p.budgetRange}`);
  if (p.interestReason) details.push(`Interested because: ${p.interestReason}`);
  if (p.objection) details.push(`Objection: ${p.objection}`);
  if (p.callbackPreference) details.push(`Callback: ${p.callbackPreference}`);

  if (details.length > 0) {
    lines.push('');
    lines.push('📋 Details');
    lines.push(details.join('\n'));
  }

  return lines.join('\n');
}
