#!/usr/bin/env bash
# Fetches project API keys and writes .env.local. Key values are never printed.
# Usage: SUPABASE_ACCESS_TOKEN=sbp_... bash scripts/fetch-keys.sh <project-ref>
set -euo pipefail

REF="${1:?project ref required}"
: "${SUPABASE_ACCESS_TOKEN:?SUPABASE_ACCESS_TOKEN required}"

RESP=$(curl -s --max-time 30 \
  -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
  "https://api.supabase.com/v1/projects/${REF}/api-keys?reveal=true")

extract() {
  # $1 = key type to match (publishable | secret)
  echo "$RESP" | node -e '
    let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{
      const keys=JSON.parse(s);
      const k=keys.find(k=>k.type===process.argv[1]);
      if(!k||!k.api_key){process.stderr.write("missing key: "+process.argv[1]+"\n");process.exit(1)}
      process.stdout.write(k.api_key);
    })' "$1"
}

PUBLISHABLE=$(extract publishable)
SECRET=$(extract secret)

cat > .env.local <<EOF
# Supabase — project ${REF}
# Generated by scripts/fetch-keys.sh. Gitignored. Do not commit.

# Safe to expose to the browser. Protected by Row Level Security.
NEXT_PUBLIC_SUPABASE_URL=https://${REF}.supabase.co
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE}

# SERVER ONLY — bypasses Row Level Security entirely.
# Never import this into a client component or prefix it with NEXT_PUBLIC_.
SUPABASE_SECRET_KEY=${SECRET}
EOF

echo "Wrote .env.local"
echo "  NEXT_PUBLIC_SUPABASE_URL      = https://${REF}.supabase.co"
echo "  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = ${PUBLISHABLE:0:16}…(${#PUBLISHABLE} chars)"
echo "  SUPABASE_SECRET_KEY           = ${SECRET:0:14}…(${#SECRET} chars)"
